/**
 * BELLA 6.0 — Documents suite.
 *
 * Create real Word (.docx), Excel (.xlsx) and PDF files from a spoken brief;
 * edit existing workbooks (add rows / set cells); build résumés; index a whole
 * folder of documents and answer questions across them (local RAG-lite).
 *
 * Zero npm dependencies: OOXML packages are assembled with the built-in zip
 * writer in util.ts, and PDFs are generated by the minimal PDF writer.
 */
import fs from "fs";
import path from "path";
import { Type } from "@google/genai";
import {
  createZip, readZip, readZipFile, escXml, createPdfBytes,
  readJson, writeJson, resolveUserPath, HOME,
} from "./util";
import type { ToolModule } from "./types";

// ---------------------------------------------------------------------------
// DOCX
// ---------------------------------------------------------------------------
export interface DocSection { heading?: string; body: string; }

function docParagraph(text: string, opts?: { bold?: boolean; size?: number; heading?: boolean }): string {
  const rPr = `<w:rPr>${opts?.bold ? "<w:b/>" : ""}${opts?.size ? `<w:sz w:val="${opts.size}"/><w:szCs w:val="${opts.size}"/>` : ""}</w:rPr>`;
  return `<w:p><w:r>${rPr}<w:t xml:space="preserve">${escXml(text)}</w:t></w:r></w:p>`;
}

export function buildDocx(title: string, sections: DocSection[]): Buffer {
  let body = "";
  if (title) body += docParagraph(title, { bold: true, size: 36 });
  for (const sec of sections) {
    if (sec.heading) body += docParagraph(sec.heading, { bold: true, size: 28 });
    for (const line of String(sec.body || "").split(/\r?\n/)) {
      body += docParagraph(line);
    }
  }
  const document =
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}` +
    `<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr>` +
    `</w:body></w:document>`;
  return createZip({
    "[Content_Types].xml":
      `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
      `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
      `<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
      `<Default Extension="xml" ContentType="application/xml"/>` +
      `<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>` +
      `</Types>`,
    "_rels/.rels":
      `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
      `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
      `<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>` +
      `</Relationships>`,
    "word/document.xml": document,
  });
}

export function createWordDocument(destPath: string, title: string, sections: DocSection[]): string {
  const p = resolveUserPath(destPath.endsWith(".docx") ? destPath : destPath + ".docx");
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, buildDocx(title, sections));
  return p;
}

// ---------------------------------------------------------------------------
// XLSX
// ---------------------------------------------------------------------------
export interface SheetData { name: string; rows: string[][]; }

function colLetter(idx: number): string {
  let s = "";
  let n = idx;
  while (n >= 0) { s = String.fromCharCode(65 + (n % 26)) + s; n = Math.floor(n / 26) - 1; }
  return s;
}

function cellXml(rowIdx: number, colIdx: number, value: string): string {
  const ref = `${colLetter(colIdx)}${rowIdx + 1}`;
  const trimmed = String(value ?? "").trim();
  if (trimmed !== "" && !isNaN(Number(trimmed)) && /^\d+(\.\d+)?$/.test(trimmed)) {
    return `<c r="${ref}"><v>${trimmed}</v></c>`;
  }
  return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${escXml(value)}</t></is></c>`;
}

function sheetXml(rows: string[][]): string {
  let body = "";
  rows.forEach((row, r) => {
    body += `<row r="${r + 1}">${row.map((v, c) => cellXml(r, c, v)).join("")}</row>`;
  });
  return (
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${body}</sheetData></worksheet>`
  );
}

export function buildXlsx(sheets: SheetData[]): Buffer {
  const entries: Record<string, string | Buffer> = {};
  const ctOverrides: string[] = [];
  const wbSheets: string[] = [];
  const rels: string[] = [];
  sheets.forEach((sheet, i) => {
    const n = i + 1;
    entries[`xl/worksheets/sheet${n}.xml`] = sheetXml(sheet.rows);
    ctOverrides.push(`<Override PartName="/xl/worksheets/sheet${n}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`);
    wbSheets.push(`<sheet name="${escXml(sheet.name || `Sheet${n}`)}" sheetId="${n}" r:id="rId${n}"/>`);
    rels.push(`<Relationship Id="rId${n}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${n}.xml"/>`);
  });
  entries["[Content_Types].xml"] =
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
    `<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
    `<Default Extension="xml" ContentType="application/xml"/>` +
    `<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>` +
    ctOverrides.join("") + `</Types>`;
  entries["_rels/.rels"] =
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
    `<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>` +
    `</Relationships>`;
  entries["xl/workbook.xml"] =
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${wbSheets.join("")}</sheets></workbook>`;
  entries["xl/_rels/workbook.xml.rels"] =
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${rels.join("")}</Relationships>`;
  return createZip(entries);
}

export function createExcelWorkbook(destPath: string, sheets: SheetData[]): string {
  const p = resolveUserPath(destPath.endsWith(".xlsx") ? destPath : destPath + ".xlsx");
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, buildXlsx(sheets));
  return p;
}

/** Parse "a,b,c" / tab separated CSV-ish row text into cells. */
function parseCsvRow(text: string): string[] {
  const sep = text.includes("\t") && !text.includes(",") ? "\t" : ",";
  const out: string[] = [];
  let cur = "";
  let inQ = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQ) {
      if (ch === '"' && text[i + 1] === '"') { cur += '"'; i++; }
      else if (ch === '"') inQ = false;
      else cur += ch;
    } else if (ch === '"') inQ = true;
    else if (ch === sep) { out.push(cur); cur = ""; }
    else cur += ch;
  }
  out.push(cur);
  return out.map(s => s.trim());
}

function colIndex(letters: string): number {
  let n = 0;
  for (const ch of letters.toUpperCase()) n = n * 26 + (ch.charCodeAt(0) - 64);
  return n - 1;
}

interface ParsedSheet { name: string; xml: string; }
function loadWorkbookSheets(xlsxPath: string): Record<string, ParsedSheet> {
  const zip = readZipFile(xlsxPath);
  const workbookXml = zip["xl/workbook.xml"]?.toString("utf-8") || "";
  const names = [...workbookXml.matchAll(/<sheet[^>]*name="([^"]*)"[^>]*r:id="rId(\d+)"/g)];
  const relsXml = zip["xl/_rels/workbook.xml.rels"]?.toString("utf-8") || "";
  const relMap = new Map([...relsXml.matchAll(/Id="rId(\d+)"[^>]*Target="(worksheets\/[^"]+)"/g)].map(m => [m[1], m[2]]));
  const sheets: Record<string, ParsedSheet> = {};
  names.forEach((m, idx) => {
    const target = relMap.get(m[2]) || `worksheets/sheet${idx + 1}.xml`;
    const key = `xl/${target}`;
    if (zip[key]) sheets[m[1]] = { name: m[1], xml: zip[key].toString("utf-8") };
  });
  if (!Object.keys(sheets).length && zip["xl/worksheets/sheet1.xml"]) {
    sheets.Sheet1 = { name: "Sheet1", xml: zip["xl/worksheets/sheet1.xml"].toString("utf-8") };
  }
  return sheets;
}

function saveWorkbookSheets(xlsxPath: string, sheets: Record<string, ParsedSheet>): void {
  const zip = readZipFile(xlsxPath);
  const entries: Record<string, string | Buffer> = {};
  for (const [k, v] of Object.entries(zip)) entries[k] = v;
  // Rewrite worksheets by original file position order.
  const workbookXml = String(entries["xl/workbook.xml"]);
  const order = [...workbookXml.matchAll(/r:id="rId(\d+)"/g)].map(m => Number(m[1]));
  const relsXml = String(entries["xl/_rels/workbook.xml.rels"]);
  const relMap = new Map([...relsXml.matchAll(/Id="rId(\d+)"[^>]*Target="(worksheets\/[^"]+)"/g)].map(m => [Number(m[1]), `xl/${m[2]}`]));
  for (const sheet of Object.values(sheets)) {
    // find its entry key by matching name in workbook order is complex; we rewrite all keys by name lookup fallback
  }
  // Simpler: overwrite each worksheet part with the parsed XML of the same name.
  const nameOrder = [...workbookXml.matchAll(/<sheet[^>]*name="([^"]*)"/g)].map(m => m[1]);
  const usedKeys = new Set<string>();
  nameOrder.forEach((nm, i) => {
    const key = relMap.get(order[i]) || `xl/worksheets/sheet${i + 1}.xml`;
    const parsed = sheets[nm] || Object.values(sheets)[i];
    if (parsed && entries[key] !== undefined) { entries[key] = parsed.xml; usedKeys.add(key); }
  });
  fs.writeFileSync(xlsxPath, createZip(entries));
}

export function excelAddRow(xlsxPath: string, sheetName: string | undefined, csvRow: string): { rowNumber: number } {
  const p = resolveUserPath(xlsxPath);
  const sheets = loadWorkbookSheets(p);
  const target = (sheetName && sheets[sheetName]) || Object.values(sheets)[0];
  if (!target) throw new Error("No worksheet found in workbook.");
  const cells = parseCsvRow(csvRow);
  const rowNums = [...target.xml.matchAll(/<row r="(\d+)"/g)].map(m => Number(m[1]));
  const newRow = (rowNums.length ? Math.max(...rowNums) : 0) + 1;
  const rowXml = `<row r="${newRow}">${cells.map((v, c) => cellXml(newRow - 1, c, v)).join("")}</row>`;
  target.xml = target.xml.replace(/<\/sheetData>/, rowXml + `</sheetData>`);
  saveWorkbookSheets(p, sheets);
  return { rowNumber: newRow };
}

export function excelSetCell(xlsxPath: string, sheetName: string | undefined, cellRef: string, value: string): void {
  const p = resolveUserPath(xlsxPath);
  const sheets = loadWorkbookSheets(p);
  const target = (sheetName && sheets[sheetName]) || Object.values(sheets)[0];
  if (!target) throw new Error("No worksheet found in workbook.");
  const m = cellRef.trim().toUpperCase().match(/^([A-Z]+)(\d+)$/);
  if (!m) throw new Error(`Invalid cell reference "${cellRef}".`);
  const col = colIndex(m[1]);
  const row = Number(m[2]);
  const newCell = cellXml(row - 1, col, value);

  // Replace existing cell or insert into the row.
  const rowMatchRe = new RegExp(`(<row r="${row}"[^>]*>)([\\s\\S]*?)(</row>)`);
  const rowMatch = target.xml.match(rowMatchRe);
  if (rowMatch) {
    const inner = rowMatch[2];
    const cellRe = new RegExp(`<c r="${m[1]}${row}"[^>]*(?:\/>|>[\\s\\S]*?<\/c>)`);
    if (cellRe.test(inner)) {
      target.xml = target.xml.replace(rowMatchRe, `$1${inner.replace(cellRe, newCell)}$3`);
    } else {
      target.xml = target.xml.replace(rowMatchRe, `$1${inner}${newCell}$3`);
    }
  } else {
    const rowXml = `<row r="${row}">${newCell}</row>`;
    target.xml = target.xml.replace(/<\/sheetData>/, rowXml + `</sheetData>`);
  }
  saveWorkbookSheets(p, sheets);
}

// ---------------------------------------------------------------------------
// PDF
// ---------------------------------------------------------------------------
export function createPdfDocument(destPath: string, title: string, sections: DocSection[]): string {
  const p = resolveUserPath(destPath.toLowerCase().endsWith(".pdf") ? destPath : destPath + ".pdf");
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, createPdfBytes(title || "Document", sections));
  return p;
}

// ---------------------------------------------------------------------------
// Résumé builder
// ---------------------------------------------------------------------------
export interface ResumeData {
  fullName: string; title?: string; email?: string; phone?: string; location?: string;
  summary?: string; skills?: string[];
  experience?: { role: string; company: string; period?: string; details?: string }[];
  education?: { degree: string; institution: string; period?: string }[];
  links?: string[];
}

function resumeSections(d: ResumeData): DocSection[] {
  const contact = [d.email, d.phone, d.location, ...(d.links || [])].filter(Boolean).join("  •  ");
  const sections: DocSection[] = [];
  if (contact) sections.push({ heading: "", body: contact });
  if (d.summary) sections.push({ heading: "SUMMARY", body: d.summary });
  if (d.skills?.length) sections.push({ heading: "SKILLS", body: d.skills.join(", ") });
  if (d.experience?.length) {
    sections.push({
      heading: "EXPERIENCE",
      body: d.experience.map(e =>
        `${e.role} — ${e.company}${e.period ? ` (${e.period})` : ""}\n${e.details || ""}`).join("\n\n"),
    });
  }
  if (d.education?.length) {
    sections.push({
      heading: "EDUCATION",
      body: d.education.map(e => `${e.degree} — ${e.institution}${e.period ? ` (${e.period})` : ""}`).join("\n"),
    });
  }
  return sections;
}

// ---------------------------------------------------------------------------
// Folder indexing / local RAG-lite
// ---------------------------------------------------------------------------
interface IndexedChunk { id: string; path: string; name: string; chunk: string; }
const INDEX_FILE = () => path.join(process.env.BELLA_DATA_DIR || process.cwd(), "doc_index.json");

const TEXT_EXTS = new Set([
  ".txt", ".md", ".py", ".js", ".ts", ".jsx", ".tsx", ".json", ".csv",
  ".html", ".htm", ".xml", ".yml", ".yaml", ".css", ".log", ".ini", ".bat", ".ps1",
]);
const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "build", "__pycache__", ".venv", "venv"]);

function extractDocxText(buf: Buffer): string {
  try {
    const xml = readZip(buf)["word/document.xml"]?.toString("utf-8") || "";
    return xml.replace(/<w:p[ >]/g, "\n<w:p ").replace(/<[^>]+>/g, "").trim();
  } catch { return ""; }
}
function extractXlsxText(buf: Buffer): string {
  try {
    const zip = readZip(buf);
    let out = "";
    for (const [k, v] of Object.entries(zip)) {
      if (k.startsWith("xl/worksheets/") || k === "xl/sharedStrings.xml") {
        out += "\n" + v.toString("utf-8").replace(/<[^>]+>/g, " ");
      }
    }
    return out.trim();
  } catch { return ""; }
}
function extractPdfText(buf: Buffer): string {
  // Best-effort for simple/generated PDFs: pull text from Tj operators.
  try {
    const raw = buf.toString("latin1");
    const matches = [...raw.matchAll(/\(([^)]+)\)\s*Tj/g)].map(m => m[1]);
    return matches.join(" ").replace(/\\([()\\])/g, "$1").trim();
  } catch { return ""; }
}

function extractText(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  try {
    const buf = fs.readFileSync(filePath);
    if (TEXT_EXTS.has(ext)) return buf.toString("utf-8");
    if (ext === ".docx") return extractDocxText(buf);
    if (ext === ".xlsx") return extractXlsxText(buf);
    if (ext === ".pdf") return extractPdfText(buf);
  } catch {}
  return "";
}

function chunkText(text: string, size = 800): string[] {
  const clean = text.replace(/\s+/g, " ").trim();
  if (!clean) return [];
  const chunks: string[] = [];
  for (let i = 0; i < clean.length; i += size) chunks.push(clean.slice(i, i + size));
  return chunks;
}

function walkFiles(dir: string, depth = 0, acc: string[] = []): string[] {
  if (depth > 6) return acc;
  let entries: fs.Dirent[] = [];
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return acc; }
  for (const e of entries) {
    if (e.isDirectory()) {
      if (!SKIP_DIRS.has(e.name) && !e.name.startsWith(".")) walkFiles(path.join(dir, e.name), depth + 1, acc);
    } else if (e.isFile()) {
      const ext = path.extname(e.name).toLowerCase();
      if (TEXT_EXTS.has(ext) || ext === ".docx" || ext === ".xlsx" || ext === ".pdf") acc.push(path.join(dir, e.name));
    }
  }
  return acc;
}

export function indexFolder(folderPath: string): { indexedFiles: number; chunks: number } {
  const root = resolveUserPath(folderPath);
  const files = walkFiles(root);
  const chunks: IndexedChunk[] = [];
  for (const f of files) {
    const text = extractText(f);
    for (const chunk of chunkText(text)) {
      chunks.push({ id: `${f}:${chunks.length}`, path: f, name: path.basename(f), chunk });
    }
  }
  writeJson(INDEX_FILE(), { root, indexedAt: new Date().toISOString(), count: chunks.length, chunks });
  return { indexedFiles: files.length, chunks: chunks.length };
}

const STOPWORDS = new Set(["the", "a", "an", "of", "in", "on", "for", "to", "and", "or", "is", "are", "was", "what", "which", "how", "my", "me", "i"]);

export function askDocuments(query: string, topK = 5): { snippets: { source: string; excerpt: string; score: number }[]; totalChunks: number } {
  const idx = readJson<{ chunks: IndexedChunk[]; count: number }>(INDEX_FILE(), { chunks: [], count: 0 });
  const terms = query.toLowerCase().split(/\W+/).filter(t => t.length > 2 && !STOPWORDS.has(t));
  const scored = idx.chunks.map(c => {
    const lower = c.chunk.toLowerCase();
    let score = 0;
    for (const t of terms) {
      const hits = lower.split(t).length - 1;
      if (hits > 0) score += hits * (1 + t.length / 20);
    }
    score /= Math.sqrt(c.chunk.length || 1);
    return { c, score };
  }).filter(s => s.score > 0).sort((a, b) => b.score - a.score).slice(0, topK);

  return {
    snippets: scored.map(s => ({
      source: `${s.c.name} (${path.dirname(s.c.path)})`,
      excerpt: s.c.chunk.slice(0, 500),
      score: Math.round(s.score * 100) / 100,
    })),
    totalChunks: idx.count,
  };
}

// ---------------------------------------------------------------------------
// Tool module
// ---------------------------------------------------------------------------
export const documentsModule: ToolModule = {
  name: "documents",
  declarations: [
    {
      name: "createWordDocument",
      description: "Create a real Microsoft Word .docx document from a spoken brief. Supports markdown-style '# ' headings inside content.",
      parameters: {
        type: Type.OBJECT,
        properties: {
          filePath: { type: Type.STRING, description: "Destination path or just a name (saved to Desktop if relative)." },
          title: { type: Type.STRING },
          content: { type: Type.STRING, description: "Full document text. Lines starting with '# ' become headings." },
        },
        required: ["filePath", "content"],
      },
    },
    {
      name: "createPdf",
      description: "Create a PDF document from text.",
      parameters: {
        type: Type.OBJECT,
        properties: {
          filePath: { type: Type.STRING },
          title: { type: Type.STRING },
          content: { type: Type.STRING },
        },
        required: ["filePath", "content"],
      },
    },
    {
      name: "createExcelWorkbook",
      description: "Create an Excel .xlsx workbook. Provide data as CSV-style text — first row becomes headers.",
      parameters: {
        type: Type.OBJECT,
        properties: {
          filePath: { type: Type.STRING },
          sheetName: { type: Type.STRING },
          csvData: { type: Type.STRING, description: "Rows separated by newlines, cells by commas." },
        },
        required: ["filePath", "csvData"],
      },
    },
    {
      name: "excelAddRow",
      description: "Append a row to an existing Excel workbook (CSV-style single row).",
      parameters: {
        type: Type.OBJECT,
        properties: {
          filePath: { type: Type.STRING },
          sheetName: { type: Type.STRING },
          rowData: { type: Type.STRING, description: "'value1,value2,value3'" },
        },
        required: ["filePath", "rowData"],
      },
    },
    {
      name: "excelSetCell",
      description: "Write one cell in an existing Excel workbook, e.g. cell 'B3' with value.",
      parameters: {
        type: Type.OBJECT,
        properties: {
          filePath: { type: Type.STRING },
          sheetName: { type: Type.STRING },
          cell: { type: Type.STRING, description: "Cell reference like B3." },
          value: { type: Type.STRING },
        },
        required: ["filePath", "cell", "value"],
      },
    },
    {
      name: "createResume",
      description: "Build a two-page résumé from structured facts as Word or PDF.",
      parameters: {
        type: Type.OBJECT,
        properties: {
          format: { type: Type.STRING, description: "'docx' (default) or 'pdf'." },
          filePath: { type: Type.STRING },
          fullName: { type: Type.STRING }, title: { type: Type.STRING },
          email: { type: Type.STRING }, phone: { type: Type.STRING }, location: { type: Type.STRING },
          summary: { type: Type.STRING },
          skills: { type: Type.ARRAY, items: { type: Type.STRING } },
          experience: { type: Type.ARRAY, items: { type: Type.STRING, description: "'Role at Company (period): details'" } },
          education: { type: Type.ARRAY, items: { type: Type.STRING, description: "'Degree at Institution (period)'" } },
        },
        required: ["fullName"],
      },
    },
    {
      name: "indexFolder",
      description: "Index a folder of documents (txt, md, code, pdf, docx, xlsx) so questions can be answered across ALL of them.",
      parameters: {
        type: Type.OBJECT,
        properties: { folderPath: { type: Type.STRING } },
        required: ["folderPath"],
      },
    },
    {
      name: "askDocuments",
      description: "Ask a question across previously indexed documents; returns the best matching excerpts with sources.",
      parameters: {
        type: Type.OBJECT,
        properties: { question: { type: Type.STRING } },
        required: ["question"],
      },
    },
  ],
  async execute(name, args) {
    switch (name) {
      case "createWordDocument": {
        const lines = String(args.content || "").split(/\r?\n/);
        const sections: DocSection[] = [{ heading: args.title || "", body: "" }];
        for (const line of lines) {
          if (/^#{1,3}\s+/.test(line)) sections.push({ heading: line.replace(/^#+\s+/, ""), body: "" });
          else sections[sections.length - 1].body += line + "\n";
        }
        const p = createWordDocument(String(args.filePath), String(args.title || ""), sections.slice(1));
        return { result: `Word document created at ${p}` };
      }
      case "createPdf": {
        const p = createPdfDocument(String(args.filePath), String(args.title || ""), [
          { heading: "", body: String(args.content || "") },
        ]);
        return { result: `PDF created at ${p}` };
      }
      case "createExcelWorkbook": {
        const rows = String(args.csvData || "").split(/\r?\n/).filter(l => l.trim()).map(parseCsvRow);
        const p = createExcelWorkbook(String(args.filePath), [{
          name: String(args.sheetName || "Sheet1"), rows,
        }]);
        return { result: `Excel workbook created at ${p} (${rows.length} rows).` };
      }
      case "excelAddRow": {
        const { rowNumber } = excelAddRow(String(args.filePath), args.sheetName, String(args.rowData));
        return { result: `Row appended as row ${rowNumber}.` };
      }
      case "excelSetCell": {
        excelSetCell(String(args.filePath), args.sheetName, String(args.cell), String(args.value ?? ""));
        return { result: `Cell ${args.cell} updated.` };
      }
      case "createResume": {
        const exps = Array.isArray(args.experience) ? (args.experience as string[]) : [];
        const edus = Array.isArray(args.education) ? (args.education as string[]) : [];
        const data: ResumeData = {
          fullName: String(args.fullName),
          email: args.email, phone: args.phone, location: args.location,
          summary: args.summary,
          skills: Array.isArray(args.skills) ? (args.skills as string[]) : [],
          experience: exps.map(line => {
            const m = line.match(/^(.*?)\s+at\s+(.*?)(?:\s*\((.*)\))?\s*[:\-]\s*(.*)$/);
            return m
              ? { role: m[1], company: m[2], period: m[3], details: m[4] }
              : { role: line.split(" at ")[0], company: line.split(" at ")[1] || "", details: "" };
          }),
          education: edus.map(line => {
            const m = line.match(/^(.*?)\s+at\s+(.*?)(?:\s*\((.*)\))?$/);
            return m ? { degree: m[1], institution: m[2], period: m[3] } : { degree: line, institution: "" };
          }),
        };
        const sections = resumeSections(data);
        const fmt = String(args.format || "docx").toLowerCase();
        const base = String(args.filePath || path.join(HOME(), "Desktop", `${data.fullName.replace(/\s+/g, "_")}_Resume`));
        const p = fmt === "pdf"
          ? createPdfDocument(base, data.fullName, [{ heading: "", body: sections.map(s => (s.heading ? `\n${s.heading}\n${s.body}` : s.body)).join("\n\n") }])
          : createWordDocument(base, data.fullName, sections);
        return { result: `Résumé (${fmt}) created at ${p}` };
      }
      case "indexFolder": {
        const stats = indexFolder(String(args.folderPath));
        return { result: `Indexed ${stats.indexedFiles} files (${stats.chunks} searchable chunks) from ${args.folderPath}. Ask me anything about them.` };
      }
      case "askDocuments": {
        const res = askDocuments(String(args.question || ""));
        if (!res.snippets.length) return { result: `Nothing relevant found across ${res.totalChunks} indexed chunks.` };
        return {
          result: res.snippets.map(s => `[${s.source}] …${s.excerpt}…`).join("\n\n"),
          totalChunks: res.totalChunks,
        };
      }
    }
    throw new Error(`Unknown documents tool: ${name}`);
  },
};
